name: 'SSH4Me'
author: 'colab-project'
description: 'Build SSH tunnel using ngrok over workflow'

runs:
  using: 'composite'
  steps:
    - name: 'Set up Docker'
      shell: bash
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: 'Build Docker image'
      shell: bash
      run: |
        docker build -t ssh4me --build-arg AUTH_TOKEN=2uLJLXorIYevJkLWToP81Kydb4g_5v28KehsBy2DY7h2ctcrX --build-arg PASSWORD=rey2000nal .

    - name: 'Run Docker container'
      shell: bash
      run: docker run docker.io/library/ssh4me

branding:
  icon: 'terminal'
  color: 'gray-dark'
